spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dying.asia:3310/user_center
    username: root
    password: root
  session:
    timeout: 86400
  redis:
    port: 6379
    host: localhost
    database: 0
knife4j:
  enable: false